version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
      - dependency-name: "suntime" # Known to be broken after this version
  groups:
    python-packages:
      patterns:
        - "*"
